$enableCippReporting = 1
$cippServerUrl = "https://cipp.example.com"
$cippTenantId = "harborviewpt.onmicrosoft.com"
$customRulesUrl = "https://check.example.com/rules/f4a7c1d2-9b3e-4c8a-a1d6-2e5b7c9f0a34.json"
$urlAllowlist = @("https://training.knowbe4.com/*", "https://*.harborviewpt.com/*")
$enableGenericWebhook = 1
$webhookUrl = "https://check.example.com/hook/f4a7c1d2-9b3e-4c8a-a1d6-2e5b7c9f0a34"
$webhookEvents = @("false_positive_report", "page_blocked", "threat_detected")
$companyName = "Example MSP"
$productName = "Example MSP Phishing Protection"
$supportEmail = "support@example.com"
$supportUrl = "https://support.example.com"
$privacyPolicyUrl = "https://example.com/privacy"
$aboutUrl = ""
$primaryColor = "#1B6FA8"
$logoUrl = "https://check.example.com/assets/f4a7c1d2-9b3e-4c8a-a1d6-2e5b7c9f0a34/logo"
$domainSquattingEnabled = 1
