<#
Deploys the Check browser extension policy for this tenant on a Windows
endpoint: force-install, pinned toolbar icon, and the full policy and
branding payload for the browsers selected below. Designed to run as
SYSTEM from an RMM. Generated by CheckDeployManager; download a fresh
copy from the tenant's Artifacts tab after any policy or branding
change, then redeploy.

Chrome and Edge read the values from HKLM policy keys on their next
policy refresh or restart; no gpupdate is needed for direct registry
writes. Firefox reads distribution\policies.json at startup. The
embedded policies.json ships install_url blank; fill it with your XPI
source per the Check docs before enabling the Firefox block, or the
force-install cannot resolve a download location.
#>

# Browser toggles: set to $false to skip a browser.
$IncludeChrome = $true
$IncludeEdge = $true
$IncludeFirefox = $true

$ErrorActionPreference = 'Stop'

function Set-CheckPolicyRegistryValue {
    param(
        [string]$Key,
        [string]$Name,
        $Value,
        [string]$Type
    )
    if (-not (Test-Path -Path $Key)) {
        New-Item -Path $Key -Force | Out-Null
    }
    New-ItemProperty -Path $Key -Name $Name -Value $Value -PropertyType $Type -Force | Out-Null
}

if ($IncludeChrome) {
    Write-Output 'Applying the Google Chrome policy values.'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Google\Chrome\ExtensionSettings\benimdeioplgkhanklclahllklceahbe' -Name 'installation_mode' -Type 'String' -Value 'force_installed'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Google\Chrome\ExtensionSettings\benimdeioplgkhanklclahllklceahbe' -Name 'update_url' -Type 'String' -Value 'https://clients2.google.com/service/update2/crx'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Google\Chrome\ExtensionSettings\benimdeioplgkhanklclahllklceahbe' -Name 'toolbar_pin' -Type 'String' -Value 'force_pinned'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Google\Chrome\3rdparty\extensions\benimdeioplgkhanklclahllklceahbe\policy' -Name 'customRulesUrl' -Type 'String' -Value 'https://check.example.com/rules/f4a7c1d2-9b3e-4c8a-a1d6-2e5b7c9f0a34.json'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Google\Chrome\3rdparty\extensions\benimdeioplgkhanklclahllklceahbe\policy' -Name 'updateInterval' -Type 'DWord' -Value 24
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Google\Chrome\3rdparty\extensions\benimdeioplgkhanklclahllklceahbe\policy' -Name 'enablePageBlocking' -Type 'DWord' -Value 1
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Google\Chrome\3rdparty\extensions\benimdeioplgkhanklclahllklceahbe\policy' -Name 'showNotifications' -Type 'DWord' -Value 1
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Google\Chrome\3rdparty\extensions\benimdeioplgkhanklclahllklceahbe\policy' -Name 'enableValidPageBadge' -Type 'DWord' -Value 1
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Google\Chrome\3rdparty\extensions\benimdeioplgkhanklclahllklceahbe\policy' -Name 'validPageBadgeTimeout' -Type 'DWord' -Value 5
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Google\Chrome\3rdparty\extensions\benimdeioplgkhanklclahllklceahbe\policy' -Name 'enableDebugLogging' -Type 'DWord' -Value 0
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Google\Chrome\3rdparty\extensions\benimdeioplgkhanklclahllklceahbe\policy' -Name 'enableCippReporting' -Type 'DWord' -Value 1
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Google\Chrome\3rdparty\extensions\benimdeioplgkhanklclahllklceahbe\policy' -Name 'cippServerUrl' -Type 'String' -Value 'https://cipp.example.com'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Google\Chrome\3rdparty\extensions\benimdeioplgkhanklclahllklceahbe\policy' -Name 'cippTenantId' -Type 'String' -Value 'harborviewpt.onmicrosoft.com'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Google\Chrome\3rdparty\extensions\benimdeioplgkhanklclahllklceahbe\policy\urlAllowlist' -Name '1' -Type 'String' -Value 'https://training.knowbe4.com/*'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Google\Chrome\3rdparty\extensions\benimdeioplgkhanklclahllklceahbe\policy\urlAllowlist' -Name '2' -Type 'String' -Value 'https://*.harborviewpt.com/*'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Google\Chrome\3rdparty\extensions\benimdeioplgkhanklclahllklceahbe\policy\genericWebhook' -Name 'enabled' -Type 'DWord' -Value 1
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Google\Chrome\3rdparty\extensions\benimdeioplgkhanklclahllklceahbe\policy\genericWebhook' -Name 'url' -Type 'String' -Value 'https://check.example.com/hook/f4a7c1d2-9b3e-4c8a-a1d6-2e5b7c9f0a34'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Google\Chrome\3rdparty\extensions\benimdeioplgkhanklclahllklceahbe\policy\genericWebhook\events' -Name '1' -Type 'String' -Value 'false_positive_report'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Google\Chrome\3rdparty\extensions\benimdeioplgkhanklclahllklceahbe\policy\genericWebhook\events' -Name '2' -Type 'String' -Value 'page_blocked'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Google\Chrome\3rdparty\extensions\benimdeioplgkhanklclahllklceahbe\policy\genericWebhook\events' -Name '3' -Type 'String' -Value 'threat_detected'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Google\Chrome\3rdparty\extensions\benimdeioplgkhanklclahllklceahbe\policy\domainSquatting' -Name 'enabled' -Type 'DWord' -Value 1
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Google\Chrome\3rdparty\extensions\benimdeioplgkhanklclahllklceahbe\policy\domainSquatting' -Name 'deviationThreshold' -Type 'DWord' -Value 2
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Google\Chrome\3rdparty\extensions\benimdeioplgkhanklclahllklceahbe\policy\domainSquatting' -Name 'Action' -Type 'String' -Value 'block'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Google\Chrome\3rdparty\extensions\benimdeioplgkhanklclahllklceahbe\policy\customBranding' -Name 'companyName' -Type 'String' -Value 'Example MSP'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Google\Chrome\3rdparty\extensions\benimdeioplgkhanklclahllklceahbe\policy\customBranding' -Name 'productName' -Type 'String' -Value 'Example MSP Phishing Protection'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Google\Chrome\3rdparty\extensions\benimdeioplgkhanklclahllklceahbe\policy\customBranding' -Name 'supportEmail' -Type 'String' -Value 'support@example.com'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Google\Chrome\3rdparty\extensions\benimdeioplgkhanklclahllklceahbe\policy\customBranding' -Name 'supportUrl' -Type 'String' -Value 'https://support.example.com'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Google\Chrome\3rdparty\extensions\benimdeioplgkhanklclahllklceahbe\policy\customBranding' -Name 'privacyPolicyUrl' -Type 'String' -Value 'https://example.com/privacy'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Google\Chrome\3rdparty\extensions\benimdeioplgkhanklclahllklceahbe\policy\customBranding' -Name 'aboutUrl' -Type 'String' -Value ''
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Google\Chrome\3rdparty\extensions\benimdeioplgkhanklclahllklceahbe\policy\customBranding' -Name 'primaryColor' -Type 'String' -Value '#1B6FA8'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Google\Chrome\3rdparty\extensions\benimdeioplgkhanklclahllklceahbe\policy\customBranding' -Name 'logoUrl' -Type 'String' -Value 'https://check.example.com/assets/f4a7c1d2-9b3e-4c8a-a1d6-2e5b7c9f0a34/logo'
}

if ($IncludeEdge) {
    Write-Output 'Applying the Microsoft Edge policy values.'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Microsoft\Edge\ExtensionSettings\knepjpocdagponkonnbggpcnhnaikajg' -Name 'installation_mode' -Type 'String' -Value 'force_installed'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Microsoft\Edge\ExtensionSettings\knepjpocdagponkonnbggpcnhnaikajg' -Name 'update_url' -Type 'String' -Value 'https://edge.microsoft.com/extensionwebstorebase/v1/crx'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Microsoft\Edge\ExtensionSettings\knepjpocdagponkonnbggpcnhnaikajg' -Name 'toolbar_state' -Type 'String' -Value 'force_shown'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Microsoft\Edge\3rdparty\extensions\knepjpocdagponkonnbggpcnhnaikajg\policy' -Name 'customRulesUrl' -Type 'String' -Value 'https://check.example.com/rules/f4a7c1d2-9b3e-4c8a-a1d6-2e5b7c9f0a34.json'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Microsoft\Edge\3rdparty\extensions\knepjpocdagponkonnbggpcnhnaikajg\policy' -Name 'updateInterval' -Type 'DWord' -Value 24
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Microsoft\Edge\3rdparty\extensions\knepjpocdagponkonnbggpcnhnaikajg\policy' -Name 'enablePageBlocking' -Type 'DWord' -Value 1
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Microsoft\Edge\3rdparty\extensions\knepjpocdagponkonnbggpcnhnaikajg\policy' -Name 'showNotifications' -Type 'DWord' -Value 1
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Microsoft\Edge\3rdparty\extensions\knepjpocdagponkonnbggpcnhnaikajg\policy' -Name 'enableValidPageBadge' -Type 'DWord' -Value 1
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Microsoft\Edge\3rdparty\extensions\knepjpocdagponkonnbggpcnhnaikajg\policy' -Name 'validPageBadgeTimeout' -Type 'DWord' -Value 5
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Microsoft\Edge\3rdparty\extensions\knepjpocdagponkonnbggpcnhnaikajg\policy' -Name 'enableDebugLogging' -Type 'DWord' -Value 0
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Microsoft\Edge\3rdparty\extensions\knepjpocdagponkonnbggpcnhnaikajg\policy' -Name 'enableCippReporting' -Type 'DWord' -Value 1
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Microsoft\Edge\3rdparty\extensions\knepjpocdagponkonnbggpcnhnaikajg\policy' -Name 'cippServerUrl' -Type 'String' -Value 'https://cipp.example.com'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Microsoft\Edge\3rdparty\extensions\knepjpocdagponkonnbggpcnhnaikajg\policy' -Name 'cippTenantId' -Type 'String' -Value 'harborviewpt.onmicrosoft.com'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Microsoft\Edge\3rdparty\extensions\knepjpocdagponkonnbggpcnhnaikajg\policy\urlAllowlist' -Name '1' -Type 'String' -Value 'https://training.knowbe4.com/*'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Microsoft\Edge\3rdparty\extensions\knepjpocdagponkonnbggpcnhnaikajg\policy\urlAllowlist' -Name '2' -Type 'String' -Value 'https://*.harborviewpt.com/*'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Microsoft\Edge\3rdparty\extensions\knepjpocdagponkonnbggpcnhnaikajg\policy\genericWebhook' -Name 'enabled' -Type 'DWord' -Value 1
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Microsoft\Edge\3rdparty\extensions\knepjpocdagponkonnbggpcnhnaikajg\policy\genericWebhook' -Name 'url' -Type 'String' -Value 'https://check.example.com/hook/f4a7c1d2-9b3e-4c8a-a1d6-2e5b7c9f0a34'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Microsoft\Edge\3rdparty\extensions\knepjpocdagponkonnbggpcnhnaikajg\policy\genericWebhook\events' -Name '1' -Type 'String' -Value 'false_positive_report'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Microsoft\Edge\3rdparty\extensions\knepjpocdagponkonnbggpcnhnaikajg\policy\genericWebhook\events' -Name '2' -Type 'String' -Value 'page_blocked'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Microsoft\Edge\3rdparty\extensions\knepjpocdagponkonnbggpcnhnaikajg\policy\genericWebhook\events' -Name '3' -Type 'String' -Value 'threat_detected'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Microsoft\Edge\3rdparty\extensions\knepjpocdagponkonnbggpcnhnaikajg\policy\domainSquatting' -Name 'enabled' -Type 'DWord' -Value 1
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Microsoft\Edge\3rdparty\extensions\knepjpocdagponkonnbggpcnhnaikajg\policy\domainSquatting' -Name 'deviationThreshold' -Type 'DWord' -Value 2
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Microsoft\Edge\3rdparty\extensions\knepjpocdagponkonnbggpcnhnaikajg\policy\domainSquatting' -Name 'Action' -Type 'String' -Value 'block'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Microsoft\Edge\3rdparty\extensions\knepjpocdagponkonnbggpcnhnaikajg\policy\customBranding' -Name 'companyName' -Type 'String' -Value 'Example MSP'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Microsoft\Edge\3rdparty\extensions\knepjpocdagponkonnbggpcnhnaikajg\policy\customBranding' -Name 'productName' -Type 'String' -Value 'Example MSP Phishing Protection'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Microsoft\Edge\3rdparty\extensions\knepjpocdagponkonnbggpcnhnaikajg\policy\customBranding' -Name 'supportEmail' -Type 'String' -Value 'support@example.com'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Microsoft\Edge\3rdparty\extensions\knepjpocdagponkonnbggpcnhnaikajg\policy\customBranding' -Name 'supportUrl' -Type 'String' -Value 'https://support.example.com'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Microsoft\Edge\3rdparty\extensions\knepjpocdagponkonnbggpcnhnaikajg\policy\customBranding' -Name 'privacyPolicyUrl' -Type 'String' -Value 'https://example.com/privacy'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Microsoft\Edge\3rdparty\extensions\knepjpocdagponkonnbggpcnhnaikajg\policy\customBranding' -Name 'aboutUrl' -Type 'String' -Value ''
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Microsoft\Edge\3rdparty\extensions\knepjpocdagponkonnbggpcnhnaikajg\policy\customBranding' -Name 'primaryColor' -Type 'String' -Value '#1B6FA8'
    Set-CheckPolicyRegistryValue -Key 'HKLM:\SOFTWARE\Policies\Microsoft\Edge\3rdparty\extensions\knepjpocdagponkonnbggpcnhnaikajg\policy\customBranding' -Name 'logoUrl' -Type 'String' -Value 'https://check.example.com/assets/f4a7c1d2-9b3e-4c8a-a1d6-2e5b7c9f0a34/logo'
}

if ($IncludeFirefox) {
    $firefoxPoliciesJson = @'
{
  "policies": {
    "Extensions": {
      "Install": [
        ""
      ],
      "Locked": [
        "check@cyberdrain.com"
      ]
    },
    "ExtensionSettings": {
      "check@cyberdrain.com": {
        "installation_mode": "force_installed",
        "install_url": "",
        "default_area": "navbar"
      }
    },
    "3rdparty": {
      "Extensions": {
        "check@cyberdrain.com": {
          "customRulesUrl": "https://check.example.com/rules/f4a7c1d2-9b3e-4c8a-a1d6-2e5b7c9f0a34.json",
          "updateInterval": 24,
          "enablePageBlocking": true,
          "showNotifications": true,
          "enableValidPageBadge": true,
          "validPageBadgeTimeout": 5,
          "enableDebugLogging": false,
          "urlAllowlist": [
            "https://training.knowbe4.com/*",
            "https://*.harborviewpt.com/*"
          ],
          "enableCippReporting": true,
          "cippServerUrl": "https://cipp.example.com",
          "cippTenantId": "harborviewpt.onmicrosoft.com",
          "genericWebhook": {
            "enabled": true,
            "url": "https://check.example.com/hook/f4a7c1d2-9b3e-4c8a-a1d6-2e5b7c9f0a34",
            "events": [
              "false_positive_report",
              "page_blocked",
              "threat_detected"
            ]
          },
          "domainSquatting": {
            "enabled": true,
            "deviationThreshold": 2,
            "Action": "block"
          },
          "customBranding": {
            "companyName": "Example MSP",
            "productName": "Example MSP Phishing Protection",
            "supportEmail": "support@example.com",
            "supportUrl": "https://support.example.com",
            "privacyPolicyUrl": "https://example.com/privacy",
            "aboutUrl": "",
            "primaryColor": "#1B6FA8",
            "logoUrl": "https://check.example.com/assets/f4a7c1d2-9b3e-4c8a-a1d6-2e5b7c9f0a34/logo"
          }
        }
      }
    }
  }
}
'@
    $firefoxInstallDirectories = @('C:\Program Files\Mozilla Firefox', 'C:\Program Files (x86)\Mozilla Firefox') | Where-Object { Test-Path -Path $_ }
    if ($null -eq $firefoxInstallDirectories) {
        Write-Output 'Firefox installation not found; skipping the Firefox block.'
    } else {
        foreach ($firefoxDirectory in @($firefoxInstallDirectories)) {
            $distributionDirectory = Join-Path -Path $firefoxDirectory -ChildPath 'distribution'
            if (-not (Test-Path -Path $distributionDirectory)) {
                New-Item -ItemType Directory -Path $distributionDirectory -Force | Out-Null
            }
            $policiesFilePath = Join-Path -Path $distributionDirectory -ChildPath 'policies.json'
            if (Test-Path -Path $policiesFilePath) {
                Copy-Item -Path $policiesFilePath -Destination ($policiesFilePath + '.bak') -Force
                Write-Output "Backed up the existing policies.json in $distributionDirectory."
            }
            Set-Content -Path $policiesFilePath -Value $firefoxPoliciesJson -Encoding Ascii
            Write-Output "Wrote policies.json to $distributionDirectory."
        }
    }
}

Write-Output 'Check policy deployment finished. Browsers apply the new policy on their next policy refresh or restart.'
