// Env is generated by `wrangler types --strict-vars=false` into
// worker-configuration.d.ts from wrangler.jsonc and .dev.vars. This alias
// keeps existing `import type { Env }` sites working. DEV_OPERATOR_EMAIL is
// typed as always present but only exists when .dev.vars provides it; readers
// must fall back (see access-jwt.ts).
export type Env = Cloudflare.Env;
